// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEAheTtFHSmmuhMJzGzcWx-QjZMYL5pRk',
    appId: '1:76141319591:web:55a0120968c09e68b05282',
    messagingSenderId: '76141319591',
    projectId: 'flutter-reg1-3f13a',
    authDomain: 'flutter-reg1-3f13a.firebaseapp.com',
    storageBucket: 'flutter-reg1-3f13a.firebasestorage.app',
    measurementId: 'G-WMDT09YJVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49nXHdzsHbGOnOj_mXb_EbyHt0BBNPqM',
    appId: '1:76141319591:android:fe9fb5db0c5cde95b05282',
    messagingSenderId: '76141319591',
    projectId: 'flutter-reg1-3f13a',
    storageBucket: 'flutter-reg1-3f13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6FSlESmZ9F4P2RTFn8NLuOVF4WQeuL8',
    appId: '1:76141319591:ios:2d85842633cd4bdcb05282',
    messagingSenderId: '76141319591',
    projectId: 'flutter-reg1-3f13a',
    storageBucket: 'flutter-reg1-3f13a.firebasestorage.app',
    iosBundleId: 'com.example.flutterRegisteration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6FSlESmZ9F4P2RTFn8NLuOVF4WQeuL8',
    appId: '1:76141319591:ios:2d85842633cd4bdcb05282',
    messagingSenderId: '76141319591',
    projectId: 'flutter-reg1-3f13a',
    storageBucket: 'flutter-reg1-3f13a.firebasestorage.app',
    iosBundleId: 'com.example.flutterRegisteration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEAheTtFHSmmuhMJzGzcWx-QjZMYL5pRk',
    appId: '1:76141319591:web:b5fa92bd08f53ac4b05282',
    messagingSenderId: '76141319591',
    projectId: 'flutter-reg1-3f13a',
    authDomain: 'flutter-reg1-3f13a.firebaseapp.com',
    storageBucket: 'flutter-reg1-3f13a.firebasestorage.app',
    measurementId: 'G-RFPHX0YF50',
  );
}
